meta_product_name: "RightTime"
meta_title: "RightTime - The Clock's Ticking..."
meta_description: "Find huge discounts on last-minute events starting really soon near you!"
meta_image: "cover" # should exist in `app/assets/images/`
twitter_account: "@righttime"   # required for Twitter Cards